security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    # role_hierarchy:
    #     ROLE_CLIENT: [ROLE_USER]
        # ROLE_ADMIN: [ROLE_CLIENT]
        # ROLE_ROOT: [ROLE_ADMIN]
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
        main:
            lazy: true
            provider: app_user_provider

         
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: "ROLE_USER" }
